# Generated by Django 3.2.6 on 2021-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0003_remove_customer_has_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_ordered_or_not',
            field=models.CharField(blank=True, default='YES', max_length=10, null=True),
        ),
    ]
