# Generated by Django 3.2.6 on 2021-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0004_customer_has_ordered_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='has_ordered_or_not',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
