# Generated by Django 3.2.6 on 2021-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queries', '0006_alter_customer_has_ordered_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Inventory',
            field=models.IntegerField(default=100),
        ),
    ]
